# Site settings
name: 江燕群
email: elvira521feng@163.com
author: YanQunJiang
url: https://elvira521feng.github.io/
resume_site: https://elvira521feng.github.io/YanQunJiang.github.io/author.md
github: https://github.com/Elvira521feng/
baseurl: "/YanQunJiang.github.io"
description: 桃之夭夭，灼灼其华
meta_description: 江燕群;个人博客;桃之夭夭，灼灼其华；
motto: 淡泊明志，宁静致远
banner: 博学而笃志,切问而近思

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Elvira521feng

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

